import {  Button, TextEdit, VerticalBox } from "std-widgets.slint";


component BoxWithLabel inherits GridLayout {
    Row {
        Text {
            text: "label text here";
        }
    }

    Row {
        @children
    }
}

export component MyApp inherits Window {
    preferred-height: 100px;
    BoxWithLabel {
        Rectangle {
            background: blue;
        }

        Rectangle {
            background: yellow;
        }
    }
}

export component MainWindow inherits Window {
    width: 326px;
    height: 326px;

    callback add_parameters <=> add_parameters.clicked;
    callback parameters_edited(string);
    in-out property <string> parameters: "";

    vb := VerticalBox {
        alignment: end;

        Text {
            text: "Enter Parameters\nLine by Line";
            font-size: 24px;
            horizontal-alignment: center;
        }

        HorizontalLayout {
            alignment: center;
            add_parameters := Button {
                text: "Add Parameters";
                clicked => {
                    root.parameters_edited(pe.text);
                }
            }
        }

        pe := TextEdit {
            font-size: 14px;
            width: parent.width;
            height: parent.height;
            text: root.parameters;
            edited(text) => {
                root.parameters_edited(text);
            }
        }
    }

}
