name: Rust CI

on:
  push:
    branches:
      - "**" # This will trigger the workflow on any branch
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry
          restore-keys: |
            ${{ runner.os }}-cargo-registry

      - name: Cache cargo build
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-${{ matrix.os }}
          restore-keys: |
            ${{ runner.os }}-cargo-build-ubuntu-latest
            ${{ runner.os }}-cargo-build-windows-latest

      - name: Build
        run: cargo build --release

      - name: Run unit tests
        run: cargo test --verbose

      - name: Upload Linux binary
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: decision_maker_linux
          path: target/release/decision_maker

      - name: Upload Windows binary
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: decision_maker_windows
          path: target\release\decision_maker.exe
